### ISSUE TITLE
"no-permission" message for commands

### ISSUE THREAD

**Issue by RedstoneFuture** [TehBrian/BuildersUtilities#31]
![grafik](https://user-images.githubusercontent.com/4140635/160238049-a4652ef5-6528-4faa-8f8a-c185155d64c7.png)

If the player does not have permission for any of the BU commands, he will get the default Minecraft message. A custom message would be great here.

`lang.yml:`

```
[...]
commands:
  no-permission: "[BU]: You do not have permission for this command."
[...]
```

**Comment by TehBrian** [comment]
This configuration option was once in the plugin, but I took it out because `paper.yml` already provides configuration for this message. [Here's the relevant commit.](https://github.com/TehBrian/BuildersUtilities/commit/81e0889e2853a52889a1eb07ddd583e155d86d55)

I'll give this issue another look later this week and maybe add it back in, though.

**Comment by RedstoneFuture** [comment]
Ok, I see. The biggest visual problem with PaperMC's message then is just not having a matching BU prefix.
